export const AIDA_COLORS = [
  { name: 'White', hex: '#fafaf7' },
  { name: 'Gray', hex: '#bdbfc2' },
  { name: 'Ivory', hex: '#f8f4e3' },
  { name: 'Oatmeal', hex: '#e6dac3' },
  { name: 'Tan', hex: '#c5ac8c' },
  { name: 'Peach', hex: '#f4d6bc' },
  { name: 'Pale Rose', hex: '#f5d9d3' },
  { name: 'Red', hex: '#c20c21' },
  { name: 'Pumpkin', hex: '#f88e4a' },
  { name: 'Lavendar', hex: '#efebf5' },
  { name: 'Violet', hex: '#b8afde' },
  { name: 'Eggplant', hex: '#683e7d' },
  { name: 'Green', hex: '#cad579' },
  { name: 'Dark Green', hex: '#145149' },
  { name: 'Sky Blue', hex: '#b6d7f4' },
  { name: 'Navy', hex: '#1a1a40' },
  { name: 'Black', hex: '#000000' },
];
