// src/database/floss/anchor.ts
export const Anchor = [
  {
    code: '292',
    name: 'Jonquil Very Light',
    hex: '#fffddc',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '293',
    name: 'Jonquil Light',
    hex: '#fefa95',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '295',
    name: 'Jonquil Medium Light',
    hex: '#fde87c',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '305',
    name: 'Topaz Light',
    hex: '#fde67f',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '297',
    name: 'Jonquil Medium',
    hex: '#ffda3e',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '298',
    name: 'Jonquil Dark',
    hex: '#febf36',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '288',
    name: 'Canary Yellow Light',
    hex: '#FCFC8E',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '289',
    name: 'Canary Yellow Medium Light',
    hex: '#FFFD6E',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '290',
    name: 'Canary Yellow Medium',
    hex: '#FFF143',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '291',
    name: 'Canary Yellow Dark',
    hex: '#FEE40B',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '275',
    name: 'Citrus Light',
    hex: '#EDE3D1',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '386',
    name: 'Citrus Very Light',
    hex: '#FDFED5',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '300',
    name: 'Citrus Very Light',
    hex: '#F7F7BC',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '301',
    name: 'Citrus',
    hex: '#FEEDA5',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '302',
    name: 'Citrus Medium Light',
    hex: '#FFCA73',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '303',
    name: 'Citrus Medium',
    hex: '#FFA54D',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '304',
    name: 'Citrus Medium',
    hex: '#FD7530',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '313',
    name: 'Tangerine Light',
    hex: '#FFB978',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '314',
    name: 'Tangerine Medium Light',
    hex: '#FA7D39',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '316',
    name: 'Tangerine Dark',
    hex: '#FF5B24',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '925',
    name: 'Tangerine Very Dark',
    hex: '#FF4F25',
    category: 'orange',
    range: '900',
    family: '1',
  },
];
