// src/database/floss/anchor.ts
export const Anchor = [
  {
    code: '292',
    name: 'Jonquil Very Light',
    hex: '#FFE9AD',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '293',
    name: 'Jonquil Light',
    hex: '#FFF1AF',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '295',
    name: 'Jonquil Medium Light',
    hex: '#FDD755',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '305',
    name: 'Topaz Light',
    hex: '#FFC840',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '297',
    name: 'Jonquil Medium',
    hex: '#FFD600',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '298',
    name: 'Jonquil Dark',
    hex: '#FFB515',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '288',
    name: 'Canary Yellow Light',
    hex: '#FFF1AF',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '289',
    name: 'Canary Yellow Medium Light',
    hex: 'f4d739',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '290',
    name: 'Canary Yellow Medium',
    hex: '#FDED54',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '291',
    name: 'Canary Yellow Dark',
    hex: '#f5c001',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '275',
    name: 'Citrus Light',
    hex: '#FFFBEF',
    category: 'yellow',
    range: '200',
    family: '1',
  },
  {
    code: '386',
    name: 'Citrus Very Light',
    hex: '#F8E4C8',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '300',
    name: 'Citrus Very Light',
    hex: '#FFE9AD',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '301',
    name: 'Citrus',
    hex: '#FFE793',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '302',
    name: 'Citrus Medium Light',
    hex: '#FFBF57',
    category: 'yellow',
    range: '300',
    family: '1',
  },
  {
    code: '303',
    name: 'Citrus Medium',
    hex: '#FFA32B',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '304',
    name: 'Citrus Medium',
    hex: '#f68703',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '313',
    name: 'Tangerine Light',
    hex: '#f4a81e',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '314',
    name: 'Tangerine Medium Light',
    hex: '#f58402',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '316',
    name: 'Tangerine Dark',
    hex: '#f87803',
    category: 'orange',
    range: '300',
    family: '1',
  },
  {
    code: '925',
    name: 'Tangerine Very Dark',
    hex: '#f25c01',
    category: 'orange',
    range: '900',
    family: '1',
  },
];
