// src/database/floss/dmc.ts
export const DMC = [
  {
    code: '3713',
    name: 'Salmon Very Light',
    hex: '#FFE2E2',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '761',
    name: 'Salmon Light',
    hex: '#FFC9C9',
    category: 'red',
    range: '700',
    family: '1',
  },
  {
    code: '760',
    name: 'Salmon',
    hex: '#F5ADAD',
    category: 'red',
    range: '700',
    family: '1',
  },
  {
    code: '3712',
    name: 'Salmon Medium',
    hex: '#F18787',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '3328',
    name: 'Salmon Dark',
    hex: '#E36D6D',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '347',
    name: 'Salmon Very Dark',
    hex: '#BF2D2D',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '353',
    name: 'Peach',
    hex: '#FED7CC',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '352',
    name: 'Coral Light',
    hex: '#FD9C97',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '351',
    name: 'Coral',
    hex: '#E96A67',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '350',
    name: 'Coral Medium',
    hex: '#E04848',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '349',
    name: 'Coral Dark',
    hex: '#D21035',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '817',
    name: 'Coral Red Very Dark',
    hex: '#BB051F',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '304',
    name: 'Red Medium',
    hex: '#B71F33',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '3833',
    name: 'Raspberry Light',
    hex: '#EA8699',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '3832',
    name: 'Raspberry Medium',
    hex: '#DB556E',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '3831',
    name: 'Raspberry Dark',
    hex: '#B32F48',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '777',
    name: 'Raspberry Very Dark',
    hex: '#913546',
    category: 'red',
    range: '700',
    family: '1',
  },
  {
    code: '3801',
    name: 'Melon Very Dark',
    hex: '#E74967',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '666',
    name: 'Bright Red',
    hex: '#E31D42',
    category: 'red',
    range: '600',
    family: '1',
  },
  {
    code: '321',
    name: 'Red',
    hex: '#C72B3B',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '498',
    name: 'Red Dark',
    hex: '#A7132B',
    category: 'red',
    range: '400',
    family: '1',
  },
  {
    code: '816',
    name: 'Garnet',
    hex: '#970B23',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '816',
    name: 'Garnet Medium',
    hex: '#87071F',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '816',
    name: 'Garnet Dark',
    hex: '#7B001B',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '894',
    name: 'Carnation Very Light',
    hex: '#FFB2BB',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '893',
    name: 'Carnation Light',
    hex: '#FC90A2',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '892',
    name: 'Carnation Medium',
    hex: '#FF798C',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '891',
    name: 'Carnation Dark',
    hex: '#FF5773',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '818',
    name: 'Baby Pink',
    hex: '#FFDFD9',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '957',
    name: 'Geranium Pale',
    hex: '#FDB5B5',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '956',
    name: 'Geranium',
    hex: '#FF9191',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '3708',
    name: 'Melon Light',
    hex: '#FFCBD5',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3706',
    name: 'Melon Medium',
    hex: '#FFADBC',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3705',
    name: 'Melon Dark',
    hex: '#FF7992',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '963',
    name: 'Dusty Rose Ultra Very Light',
    hex: '#FFD7D7',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '3716',
    name: 'Dusty Rose Medium Very Light',
    hex: '#FFBDBD',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '962',
    name: 'Dusty Rose Medium',
    hex: '#E68A8A',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '961',
    name: 'Dusty Rose Dark',
    hex: '#CF7373',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '309',
    name: 'Rose Dark',
    hex: '#BA4A4A',
    category: 'pink',
    range: '300',
    family: '2',
  },
  {
    code: '819',
    name: 'Baby Pink light',
    hex: '#FFEEEB',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '3326',
    name: 'Rose Light',
    hex: '#FBADB4',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '899',
    name: 'Rose Medium',
    hex: '#F27688',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '335',
    name: 'Rose',
    hex: '#EE546E',
    category: 'pink',
    range: '300',
    family: '2',
  },
  {
    code: '336',
    name: 'Rose Very Dark',
    hex: '#B33B4B',
    category: 'pink',
    range: '300',
    family: '2',
  },
  {
    code: '151',
    name: 'Dusty Rose Very Light',
    hex: '#F0CED4',
    category: 'pink',
    range: '100',
    family: '2',
  },
  {
    code: '3354',
    name: 'Dusty Rose Light',
    hex: '#E4A6AC',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3733',
    name: 'Dusty Rose',
    hex: '#E8879B',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3731',
    name: 'Dusty Rose Very Dark',
    hex: '#DA6783',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3350',
    name: 'Dusty Rose Ultra Dark',
    hex: '#BC4365',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '150',
    name: 'Dusty Rose Ultra Very Dark',
    hex: '#AB0249',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '23',
    name: 'Apple Blossom',
    hex: '#EDE2ED',
    category: 'fuchsia',
    range: '20',
    family: '3',
  },
  {
    code: '3689',
    name: 'Mauve Light',
    hex: '#FBBFC2',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3688',
    name: 'Mauve Medium',
    hex: '#E7A9AC',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3687',
    name: 'Mauve',
    hex: '#C96B70',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3803',
    name: 'Mauve Dark',
    hex: '#AB3357',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3685',
    name: 'Mauve Very Dark',
    hex: '#881531',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '605',
    name: 'Cranberry Very Light',
    hex: '#FFC0CD',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '604',
    name: 'Cranberry Light',
    hex: '#FFB0BE',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '603',
    name: 'Cranberry',
    hex: '#FFA4BE',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '602',
    name: 'Cranberry Medium',
    hex: '#E24874',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '601',
    name: 'Cranberry Dark',
    hex: '#D1286A',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '600',
    name: 'Cranberry Very Dark',
    hex: '#CD2F63',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '3806',
    name: 'Cyclamen Pink Light',
    hex: '#FF8CAE',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3805',
    name: 'Cyclamen Pink',
    hex: '#F3478B',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3804',
    name: 'Cyclamen Pink Dark',
    hex: '#E02876',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3609',
    name: 'Plum Ultra Light',
    hex: '#F4AED7',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3608',
    name: 'Plum Very Light',
    hex: '#EA9CC4',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3607',
    name: 'Plum Light',
    hex: '#C54989',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '718',
    name: 'Plum',
    hex: '#9C2462',
    category: 'fuchsia',
    range: '700',
    family: '3',
  },
  {
    code: '917',
    name: 'Plum Medium',
    hex: '#9B1359',
    category: 'fuchsia',
    range: '900',
    family: '3',
  },
  {
    code: '915',
    name: 'Plum Dark',
    hex: '#820043',
    category: 'fuchsia',
    range: '900',
    family: '3',
  },
  {
    code: '33',
    name: 'Fuschia',
    hex: '#9C599C',
    category: 'fuchsia',
    range: '30',
    family: '3',
  },
  {
    code: '34',
    name: 'Fuschia Dark',
    hex: '#7D3064',
    category: 'fuchsia',
    range: '30',
    family: '3',
  },
  {
    code: '35',
    name: 'Fuschia Very Dark',
    hex: '#46052D',
    category: 'fuchsia',
    range: '30',
    family: '3',
  },
  {
    code: '778',
    name: 'Antique Mauve Very Light',
    hex: '#DFB3BB',
    category: 'purple',
    range: '700',
    family: '4',
  },
  {
    code: '3727',
    name: 'Antique Mauve Light',
    hex: '#DBA9B2',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '316',
    name: 'Antique Mauve Medium',
    hex: '#B7737F',
    category: 'purple',
    range: '300',
    family: '4',
  },
  {
    code: '3726',
    name: 'Antique Mauve Dark',
    hex: '#9B5B66',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '315',
    name: 'Antique Mauve Medium Dark',
    hex: '#814952',
    category: 'purple',
    range: '300',
    family: '4',
  },
  {
    code: '3802',
    name: 'Antique Mauve Very Dark',
    hex: '#714149',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '902',
    name: 'Garnet Very Dark',
    hex: '#822637',
    category: 'purple',
    range: '900',
    family: '4',
  },
  {
    code: '3836',
    name: 'Grape Light',
    hex: '#BA91AA',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '3835',
    name: 'Grape Medium',
    hex: '#946083',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '3834',
    name: 'Grape Dark',
    hex: '#72375D',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '154',
    name: 'Grape Very Dark',
    hex: '#572433',
    category: 'purple',
    range: '100',
    family: '4',
  },
  {
    code: '24',
    name: 'White Lavender',
    hex: '#E0D7EE',
    category: 'purple',
    range: '20',
    family: '4',
  },
  {
    code: '25',
    name: 'Lavender Ultra Light',
    hex: '#DAD2E9',
    category: 'purple',
    range: '20',
    family: '4',
  },
  {
    code: '26',
    name: 'Lavender Pale',
    hex: '#D7CAE6',
    category: 'purple',
    range: '20',
    family: '4',
  },
  {
    code: '211',
    name: 'Lavender Light',
    hex: '#E3CBE3',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '210',
    name: 'Lavender Medium',
    hex: '#D29FC3',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '209',
    name: 'Lavender Dark',
    hex: '#A37BA7',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '208',
    name: 'Lavender Very Dark',
    hex: '#835B8B',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '3837',
    name: 'Lavender Ultra Dark',
    hex: '#6C3A6E',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '327',
    name: 'Violet Dark',
    hex: '#633666',
    category: 'purple',
    range: '300',
    family: '4',
  },
  {
    code: '153',
    name: 'Violet Very Light',
    hex: '#E6CCD9',
    category: 'purple',
    range: '100',
    family: '4',
  },
  {
    code: '554',
    name: 'Violet Light',
    hex: '#DBB3CB',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '553',
    name: 'Violet',
    hex: '#A3638B',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '552',
    name: 'Violet Medium',
    hex: '#803A6B',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '550',
    name: 'Violet Very Dark',
    hex: '#5C184E',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '3743',
    name: 'Antique Violet Very Light',
    hex: '#D7CBD3',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '3742',
    name: 'Antique Violet Light',
    hex: '#B79DA7',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '3741',
    name: 'Antique Violet Medium',
    hex: '#956F7C',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '3740',
    name: 'Antique Violet Dark',
    hex: '#785762',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '27',
    name: 'White Violet',
    hex: '#F0EEF9',
    category: 'blue-violet',
    range: '20',
    family: '5',
  },
  {
    code: '28',
    name: 'Eggplant Medium Light',
    hex: '#9086A9',
    category: 'blue-violet',
    range: '20',
    family: '5',
  },
  {
    code: '3747',
    name: 'Blue Violet Very Light',
    hex: '#D3D7ED',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '341',
    name: 'Blue Violet Light',
    hex: '#B7BFDD',
    category: 'blue-violet',
    range: '300',
    family: '5',
  },
  {
    code: '156',
    name: 'Blue Violet Medium Light',
    hex: '#A3AED1',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '340',
    name: 'Blue Violet Medium',
    hex: '#ADA7C7',
    category: 'blue-violet',
    range: '300',
    family: '5',
  },
  {
    code: '155',
    name: 'Blue Violet Medium Dark',
    hex: '#9891B6',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '3746',
    name: 'Blue Violet Dark',
    hex: '#776B98',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '333',
    name: 'Blue Violet Very Dark',
    hex: '#5C5478',
    category: 'blue-violet',
    range: '300',
    family: '5',
  },
  {
    code: '30',
    name: 'Blueberry Medium Light',
    hex: '#7D77A5',
    category: 'blue-violet',
    range: '30',
    family: '5',
  },
  {
    code: '31',
    name: 'Blueberry',
    hex: '#50518D',
    category: 'blue-violet',
    range: '30',
    family: '5',
  },
  {
    code: '32',
    name: 'Blueberry Dark',
    hex: '#4D2E8A',
    category: 'blue-violet',
    range: '30',
    family: '5',
  },
  {
    code: '157',
    name: 'Cornflower Blue Very Light',
    hex: '#BBC3D9',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '794',
    name: 'Cornflower Blue Light',
    hex: '#8F9CC1',
    category: 'blue-violet',
    range: '700',
    family: '5',
  },
  {
    code: '793',
    name: 'Cornflower Blue Medium',
    hex: '#707DA2',
    category: 'blue-violet',
    range: '700',
    family: '5',
  },
  {
    code: '3807',
    name: 'Cornflower Blue',
    hex: '#60678C',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '792',
    name: 'Cornflower Blue Dark',
    hex: '#555B7B',
    category: 'blue-violet',
    range: '700',
    family: '5',
  },
  {
    code: '158',
    name: 'Blue Dark',
    hex: '#4C526E',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '791',
    name: 'Cornflower Blue Very Dark',
    hex: '#464563',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '3840',
    name: 'Lavender Blue Light',
    hex: '#B0C0DA',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3839',
    name: 'Lavender Blue Medium',
    hex: '#7B8EAB',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3838',
    name: 'Lavender Blue Dark',
    hex: '#5C7294',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '800',
    name: 'Delft Blue Pale',
    hex: '#C0CCDE',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '809',
    name: 'Delft Blue',
    hex: '#94A8C6',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '799',
    name: 'Delft Blue Medium',
    hex: '#748EB6',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '798',
    name: 'Delft Blue Dark',
    hex: '#466A8E',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '797',
    name: 'Royal Blue',
    hex: '#13477D',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '796',
    name: 'Royal Blue Dark',
    hex: '#11416D',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '820',
    name: 'Royal Blue Very Dark',
    hex: '#0E365C',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '162',
    name: 'Blue Ultra Very Light',
    hex: '#DBECF5',
    category: 'blue',
    range: '100',
    family: '6',
  },
  {
    code: '827',
    name: 'Blue Very Light',
    hex: '#BDDDED',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '813',
    name: 'Blue Light',
    hex: '#A1C2D7',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '826',
    name: 'Blue Medium',
    hex: '#6B9EBF',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '825',
    name: 'Blue Dark',
    hex: '#4781A5',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '824',
    name: 'Blue Very Dark',
    hex: '#396987',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '996',
    name: 'Electric Blue Medium',
    hex: '#30C2EC',
    category: 'blue',
    range: '900',
    family: '6',
  },
  {
    code: '3843',
    name: 'Electric Blue',
    hex: '#14AAD0',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '995',
    name: 'Electric Blue Dark',
    hex: '#2696B6',
    category: 'blue',
    range: '900',
    family: '6',
  },
  {
    code: '3846',
    name: 'Turquoise Bright Light',
    hex: '#06E3E6',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3845',
    name: 'Turquoise Bright Medium',
    hex: '#04C4CA',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3844',
    name: 'Turquoise Bright Dark',
    hex: '#12AEBA',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '159',
    name: 'Blue Gray Light',
    hex: '#C7CAD7',
    category: 'sapphire',
    range: '100',
    family: '7',
  },
  {
    code: '160',
    name: 'Blue Gray Medium',
    hex: '#999FB7',
    category: 'sapphire',
    range: '100',
    family: '7',
  },
  {
    code: '161',
    name: 'Blue Gray',
    hex: '#7880A4',
    category: 'sapphire',
    range: '100',
    family: '7',
  },
  {
    code: '3756',
    name: 'Baby Blue Ultra Very Light',
    hex: '#EEFCFC',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '775',
    name: 'Baby Blue Very Light',
    hex: '#D9EBF1',
    category: 'sapphire',
    range: '700',
    family: '7',
  },
  {
    code: '3841',
    name: 'Baby Blue Pale',
    hex: '#CDDFED',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '3325',
    name: 'Baby Blue Light',
    hex: '#B8D2E6',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '3755',
    name: 'Baby Blue',
    hex: '#92B4CE',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '334',
    name: 'Baby Blue Medium',
    hex: '#739FC1',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '322',
    name: 'Baby Blue Dark',
    hex: '#5A8FB8',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '312',
    name: 'Baby Blue Very Dark',
    hex: '#35668B',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '803',
    name: 'Baby Blue Ultra Very Dark',
    hex: '#2C597C',
    category: 'sapphire',
    range: '800',
    family: '7',
  },
  {
    code: '336',
    name: 'Navy Blue',
    hex: '#253B73',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '823',
    name: 'Navy Blue Dark',
    hex: '#213063',
    category: 'sapphire',
    range: '800',
    family: '7',
  },
  {
    code: '939',
    name: 'Navy Blue Very Dark',
    hex: '#1B2853',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '3753',
    name: 'Antique Blue Ultra Very Light',
    hex: '#DBE2E9',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '3752',
    name: 'Antique Blue Very Light',
    hex: '#C7D1DB',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '932',
    name: 'Antique Blue Light',
    hex: '#A2B5C6',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '931',
    name: 'Antique Blue Medium',
    hex: '#6A859E',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '930',
    name: 'Antique Blue Dark',
    hex: '#455C71',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '3750',
    name: 'Antique Blue Very Dark',
    hex: '#384C5E',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '828',
    name: 'Sky Blue Very Light',
    hex: '#C5E8ED',
    category: 'blue-green',
    range: '800',
    family: '8',
  },
  {
    code: '3761',
    name: 'Sky Blue Light',
    hex: '#ACD8E2',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '519',
    name: 'Sky Blue',
    hex: '#7EB1C8',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '518',
    name: 'Wedgewood Light',
    hex: '#4F93A7',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '3760',
    name: 'Wedgewood Medium',
    hex: '#3E85A2',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '517',
    name: 'Wedgewood Dark',
    hex: '#3B768F',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '3842',
    name: 'Wedgewood Very Dark',
    hex: '#32667C',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '311',
    name: 'Wedgewood Ultra Very Dark',
    hex: '#1C5066',
    category: 'blue-green',
    range: '300',
    family: '8',
  },
  {
    code: '747',
    name: 'Peacock Blue Very Light',
    hex: '#E5FCFD',
    category: 'blue-green',
    range: '700',
    family: '8',
  },
  {
    code: '3766',
    name: 'Peacock Blue Light',
    hex: '#99CFD9',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '807',
    name: 'Peacock Blue',
    hex: '#64ABBA',
    category: 'blue-green',
    range: '800',
    family: '8',
  },
  {
    code: '806',
    name: 'Peacock Blue Dark',
    hex: '#3D95A5',
    category: 'blue-green',
    range: '800',
    family: '8',
  },
  {
    code: '3765',
    name: 'Peacock Blue Very Dark',
    hex: '#347F8C',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3811',
    name: 'Turquoise Very Light',
    hex: '#BCE3E6',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '598',
    name: 'Turquoise Light',
    hex: '#90C3CC',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '597',
    name: 'Turquoise',
    hex: '#5BA3B3',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '3810',
    name: 'Turquoise Dark',
    hex: '#488E9A',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3809',
    name: 'Turquoise Very Dark',
    hex: '#3F7C85',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3808',
    name: 'Turquoise Ultra Very Dark',
    hex: '#366970',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '928',
    name: 'Gray Green Very Light',
    hex: '#DDE3E3',
    category: 'blue-green',
    range: '900',
    family: '8',
  },
  {
    code: '927',
    name: 'Gray Green Light',
    hex: '#BDCBCB',
    category: 'blue-green',
    range: '900',
    family: '8',
  },
  {
    code: '926',
    name: 'Gray Green Medium',
    hex: '#98AEAE',
    category: 'blue-green',
    range: '900',
    family: '8',
  },
  {
    code: '3768',
    name: 'Gray Green Dark',
    hex: '#657F7F',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3849',
    name: 'Teal Green Light',
    hex: '#52B3AE',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3848',
    name: 'Teal Green Medium',
    hex: '#419392',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3847',
    name: 'Teal Green Dark',
    hex: '#347D75',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '964',
    name: 'Sea Green Light',
    hex: '#347D75',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '959',
    name: 'Sea Green Medium',
    hex: '#59C7B4',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '958',
    name: 'Sea Green Dark',
    hex: '#3EB6A1',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '3812',
    name: 'Sea Green Very Dark',
    hex: '#2F8C84',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '3851',
    name: 'Green Bright Light',
    hex: '#49B3A1',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '943',
    name: 'Green Bright Medium',
    hex: '#3D9384',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '3850',
    name: 'Green Bright Dark',
    hex: '#378477',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '993',
    name: 'Aquamarine Very Light',
    hex: '#90C0B4',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '992',
    name: 'Aquamarine Light',
    hex: '#6FAE9F',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '3814',
    name: 'Aquamarine',
    hex: '#508B7D',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '991',
    name: 'Aquamarine Dark',
    hex: '#477B6E',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '966',
    name: 'Jade Ultra Very Light',
    hex: '#B9D7C0',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '564',
    name: 'Jade Very Light',
    hex: '#A7CDAF',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '564',
    name: 'Jade Very Light',
    hex: '#A7CDAF',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '563',
    name: 'Jade Light',
    hex: '#8FC098',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '562',
    name: 'Jade Medium',
    hex: '#53976A',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '505',
    name: 'Jade Green',
    hex: '#338362',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '3817',
    name: 'Celadon Green Light',
    hex: '#99C3AA',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '3816',
    name: 'Celadon Green',
    hex: '#65A57D',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '163',
    name: 'Celadon Green Medium',
    hex: '#4D8361',
    category: 'green',
    range: '100',
    family: '9',
  },
  {
    code: '3815',
    name: 'Celadon Green Dark',
    hex: '#477759',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '561',
    name: 'Celadon Green Very Dark',
    hex: '#2C6A45',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '504',
    name: 'Blue Green Very Light',
    hex: '#C4DECC',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '3813',
    name: 'Blue Green Light',
    hex: '#B2D4BD',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '503',
    name: 'Blue Green Medium',
    hex: '#7BAC94',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '502',
    name: 'Blue Green',
    hex: '#5B9071',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '501',
    name: 'Blue Green Dark',
    hex: '#396F52',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '500',
    name: 'Blue Green Very Dark',
    hex: '#044D33',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '310',
    name: 'Black',
    hex: '#000000',
    category: 'neutral',
    range: '300',
    family: '20',
  },
];
