// src/database/floss/dmc.ts
export const DMC = [
  {
    code: '3713',
    name: 'Salmon Very Light',
    hex: '#FFE2E2',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '761',
    name: 'Salmon Light',
    hex: '#FFC9C9',
    category: 'red',
    range: '700',
    family: '1',
  },
  {
    code: '760',
    name: 'Salmon',
    hex: '#F5ADAD',
    category: 'red',
    range: '700',
    family: '1',
  },
  {
    code: '3712',
    name: 'Salmon Medium',
    hex: '#F18787',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '3328',
    name: 'Salmon Dark',
    hex: '#E36D6D',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '347',
    name: 'Salmon Very Dark',
    hex: '#BF2D2D',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '353',
    name: 'Peach',
    hex: '#FED7CC',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '352',
    name: 'Coral Light',
    hex: '#FD9C97',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '351',
    name: 'Coral',
    hex: '#E96A67',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '350',
    name: 'Coral Medium',
    hex: '#E04848',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '349',
    name: 'Coral Dark',
    hex: '#D21035',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '817',
    name: 'Coral Red Very Dark',
    hex: '#BB051F',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '304',
    name: 'Red Medium',
    hex: '#B71F33',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '3833',
    name: 'Raspberry Light',
    hex: '#EA8699',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '3832',
    name: 'Raspberry Medium',
    hex: '#DB556E',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '3831',
    name: 'Raspberry Dark',
    hex: '#B32F48',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '777',
    name: 'Raspberry Very Dark',
    hex: '#913546',
    category: 'red',
    range: '700',
    family: '1',
  },
  {
    code: '3801',
    name: 'Melon Very Dark',
    hex: '#E74967',
    category: 'red',
    range: '3000',
    family: '1',
  },
  {
    code: '666',
    name: 'Bright Red',
    hex: '#E31D42',
    category: 'red',
    range: '600',
    family: '1',
  },
  {
    code: '321',
    name: 'Red',
    hex: '#C72B3B',
    category: 'red',
    range: '300',
    family: '1',
  },
  {
    code: '498',
    name: 'Red Dark',
    hex: '#A7132B',
    category: 'red',
    range: '400',
    family: '1',
  },
  {
    code: '816',
    name: 'Garnet',
    hex: '#970B23',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '816',
    name: 'Garnet Medium',
    hex: '#87071F',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '816',
    name: 'Garnet Dark',
    hex: '#7B001B',
    category: 'red',
    range: '800',
    family: '1',
  },
  {
    code: '894',
    name: 'Carnation Very Light',
    hex: '#FFB2BB',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '893',
    name: 'Carnation Light',
    hex: '#FC90A2',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '892',
    name: 'Carnation Medium',
    hex: '#FF798C',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '891',
    name: 'Carnation Dark',
    hex: '#FF5773',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '818',
    name: 'Baby Pink',
    hex: '#FFDFD9',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '957',
    name: 'Geranium Pale',
    hex: '#FDB5B5',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '956',
    name: 'Geranium',
    hex: '#FF9191',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '3708',
    name: 'Melon Light',
    hex: '#FFCBD5',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3706',
    name: 'Melon Medium',
    hex: '#FFADBC',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3705',
    name: 'Melon Dark',
    hex: '#FF7992',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '963',
    name: 'Dusty Rose Ultra Very Light',
    hex: '#FFD7D7',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '3716',
    name: 'Dusty Rose Medium Very Light',
    hex: '#FFBDBD',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '962',
    name: 'Dusty Rose Medium',
    hex: '#E68A8A',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '961',
    name: 'Dusty Rose Dark',
    hex: '#CF7373',
    category: 'pink',
    range: '900',
    family: '2',
  },
  {
    code: '309',
    name: 'Rose Dark',
    hex: '#BA4A4A',
    category: 'pink',
    range: '300',
    family: '2',
  },
  {
    code: '819',
    name: 'Baby Pink light',
    hex: '#FFEEEB',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '3326',
    name: 'Rose Light',
    hex: '#FBADB4',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '899',
    name: 'Rose Medium',
    hex: '#F27688',
    category: 'pink',
    range: '800',
    family: '2',
  },
  {
    code: '335',
    name: 'Rose',
    hex: '#EE546E',
    category: 'pink',
    range: '300',
    family: '2',
  },
  {
    code: '336',
    name: 'Rose Very Dark',
    hex: '#B33B4B',
    category: 'pink',
    range: '300',
    family: '2',
  },
  {
    code: '151',
    name: 'Dusty Rose Very Light',
    hex: '#F0CED4',
    category: 'pink',
    range: '100',
    family: '2',
  },
  {
    code: '3354',
    name: 'Dusty Rose Light',
    hex: '#E4A6AC',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3733',
    name: 'Dusty Rose',
    hex: '#E8879B',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3731',
    name: 'Dusty Rose Very Dark',
    hex: '#DA6783',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '3350',
    name: 'Dusty Rose Ultra Dark',
    hex: '#BC4365',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '150',
    name: 'Dusty Rose Ultra Very Dark',
    hex: '#AB0249',
    category: 'pink',
    range: '3000',
    family: '2',
  },
  {
    code: '23',
    name: 'Apple Blossom',
    hex: '#EDE2ED',
    category: 'fuchsia',
    range: '20',
    family: '3',
  },
  {
    code: '3689',
    name: 'Mauve Light',
    hex: '#FBBFC2',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3688',
    name: 'Mauve Medium',
    hex: '#E7A9AC',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3687',
    name: 'Mauve',
    hex: '#C96B70',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3803',
    name: 'Mauve Dark',
    hex: '#AB3357',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3685',
    name: 'Mauve Very Dark',
    hex: '#881531',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '605',
    name: 'Cranberry Very Light',
    hex: '#FFC0CD',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '604',
    name: 'Cranberry Light',
    hex: '#FFB0BE',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '603',
    name: 'Cranberry',
    hex: '#FFA4BE',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '602',
    name: 'Cranberry Medium',
    hex: '#E24874',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '601',
    name: 'Cranberry Dark',
    hex: '#D1286A',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '600',
    name: 'Cranberry Very Dark',
    hex: '#CD2F63',
    category: 'fuchsia',
    range: '600',
    family: '3',
  },
  {
    code: '3806',
    name: 'Cyclamen Pink Light',
    hex: '#FF8CAE',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3805',
    name: 'Cyclamen Pink',
    hex: '#F3478B',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3804',
    name: 'Cyclamen Pink Dark',
    hex: '#E02876',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3609',
    name: 'Plum Ultra Light',
    hex: '#F4AED7',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3608',
    name: 'Plum Very Light',
    hex: '#EA9CC4',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '3607',
    name: 'Plum Light',
    hex: '#C54989',
    category: 'fuchsia',
    range: '3000',
    family: '3',
  },
  {
    code: '718',
    name: 'Plum',
    hex: '#9C2462',
    category: 'fuchsia',
    range: '700',
    family: '3',
  },
  {
    code: '917',
    name: 'Plum Medium',
    hex: '#9B1359',
    category: 'fuchsia',
    range: '900',
    family: '3',
  },
  {
    code: '915',
    name: 'Plum Dark',
    hex: '#820043',
    category: 'fuchsia',
    range: '900',
    family: '3',
  },
  {
    code: '33',
    name: 'Fuschia',
    hex: '#9C599C',
    category: 'fuchsia',
    range: '30',
    family: '3',
  },
  {
    code: '34',
    name: 'Fuschia Dark',
    hex: '#7D3064',
    category: 'fuchsia',
    range: '30',
    family: '3',
  },
  {
    code: '35',
    name: 'Fuschia Very Dark',
    hex: '#46052D',
    category: 'fuchsia',
    range: '30',
    family: '3',
  },
  {
    code: '778',
    name: 'Antique Mauve Very Light',
    hex: '#DFB3BB',
    category: 'purple',
    range: '700',
    family: '4',
  },
  {
    code: '3727',
    name: 'Antique Mauve Light',
    hex: '#DBA9B2',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '316',
    name: 'Antique Mauve Medium',
    hex: '#B7737F',
    category: 'purple',
    range: '300',
    family: '4',
  },
  {
    code: '3726',
    name: 'Antique Mauve Dark',
    hex: '#9B5B66',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '315',
    name: 'Antique Mauve Medium Dark',
    hex: '#814952',
    category: 'purple',
    range: '300',
    family: '4',
  },
  {
    code: '3802',
    name: 'Antique Mauve Very Dark',
    hex: '#714149',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '902',
    name: 'Garnet Very Dark',
    hex: '#822637',
    category: 'purple',
    range: '900',
    family: '4',
  },
  {
    code: '3836',
    name: 'Grape Light',
    hex: '#BA91AA',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '3835',
    name: 'Grape Medium',
    hex: '#946083',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '3834',
    name: 'Grape Dark',
    hex: '#72375D',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '154',
    name: 'Grape Very Dark',
    hex: '#572433',
    category: 'purple',
    range: '100',
    family: '4',
  },
  {
    code: '24',
    name: 'White Lavender',
    hex: '#E0D7EE',
    category: 'purple',
    range: '20',
    family: '4',
  },
  {
    code: '25',
    name: 'Lavender Ultra Light',
    hex: '#DAD2E9',
    category: 'purple',
    range: '20',
    family: '4',
  },
  {
    code: '26',
    name: 'Lavender Pale',
    hex: '#D7CAE6',
    category: 'purple',
    range: '20',
    family: '4',
  },
  {
    code: '211',
    name: 'Lavender Light',
    hex: '#E3CBE3',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '210',
    name: 'Lavender Medium',
    hex: '#D29FC3',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '209',
    name: 'Lavender Dark',
    hex: '#A37BA7',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '208',
    name: 'Lavender Very Dark',
    hex: '#835B8B',
    category: 'purple',
    range: '200',
    family: '4',
  },
  {
    code: '3837',
    name: 'Lavender Ultra Dark',
    hex: '#6C3A6E',
    category: 'purple',
    range: '3000',
    family: '4',
  },
  {
    code: '327',
    name: 'Violet Dark',
    hex: '#633666',
    category: 'purple',
    range: '300',
    family: '4',
  },
  {
    code: '153',
    name: 'Violet Very Light',
    hex: '#E6CCD9',
    category: 'purple',
    range: '100',
    family: '4',
  },
  {
    code: '554',
    name: 'Violet Light',
    hex: '#DBB3CB',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '553',
    name: 'Violet',
    hex: '#A3638B',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '552',
    name: 'Violet Medium',
    hex: '#803A6B',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '550',
    name: 'Violet Very Dark',
    hex: '#5C184E',
    category: 'purple',
    range: '500',
    family: '4',
  },
  {
    code: '3743',
    name: 'Antique Violet Very Light',
    hex: '#D7CBD3',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '3742',
    name: 'Antique Violet Light',
    hex: '#B79DA7',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '3741',
    name: 'Antique Violet Medium',
    hex: '#956F7C',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '3740',
    name: 'Antique Violet Dark',
    hex: '#785762',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '27',
    name: 'White Violet',
    hex: '#F0EEF9',
    category: 'blue-violet',
    range: '20',
    family: '5',
  },
  {
    code: '28',
    name: 'Eggplant Medium Light',
    hex: '#9086A9',
    category: 'blue-violet',
    range: '20',
    family: '5',
  },
  {
    code: '3747',
    name: 'Blue Violet Very Light',
    hex: '#D3D7ED',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '341',
    name: 'Blue Violet Light',
    hex: '#B7BFDD',
    category: 'blue-violet',
    range: '300',
    family: '5',
  },
  {
    code: '156',
    name: 'Blue Violet Medium Light',
    hex: '#A3AED1',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '340',
    name: 'Blue Violet Medium',
    hex: '#ADA7C7',
    category: 'blue-violet',
    range: '300',
    family: '5',
  },
  {
    code: '155',
    name: 'Blue Violet Medium Dark',
    hex: '#9891B6',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '3746',
    name: 'Blue Violet Dark',
    hex: '#776B98',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '333',
    name: 'Blue Violet Very Dark',
    hex: '#5C5478',
    category: 'blue-violet',
    range: '300',
    family: '5',
  },
  {
    code: '30',
    name: 'Blueberry Medium Light',
    hex: '#7D77A5',
    category: 'blue-violet',
    range: '30',
    family: '5',
  },
  {
    code: '31',
    name: 'Blueberry',
    hex: '#50518D',
    category: 'blue-violet',
    range: '30',
    family: '5',
  },
  {
    code: '32',
    name: 'Blueberry Dark',
    hex: '#4D2E8A',
    category: 'blue-violet',
    range: '30',
    family: '5',
  },
  {
    code: '157',
    name: 'Cornflower Blue Very Light',
    hex: '#BBC3D9',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '794',
    name: 'Cornflower Blue Light',
    hex: '#8F9CC1',
    category: 'blue-violet',
    range: '700',
    family: '5',
  },
  {
    code: '793',
    name: 'Cornflower Blue Medium',
    hex: '#707DA2',
    category: 'blue-violet',
    range: '700',
    family: '5',
  },
  {
    code: '3807',
    name: 'Cornflower Blue',
    hex: '#60678C',
    category: 'blue-violet',
    range: '3000',
    family: '5',
  },
  {
    code: '792',
    name: 'Cornflower Blue Dark',
    hex: '#555B7B',
    category: 'blue-violet',
    range: '700',
    family: '5',
  },
  {
    code: '158',
    name: 'Blue Dark',
    hex: '#4C526E',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '791',
    name: 'Cornflower Blue Very Dark',
    hex: '#464563',
    category: 'blue-violet',
    range: '100',
    family: '5',
  },
  {
    code: '3840',
    name: 'Lavender Blue Light',
    hex: '#B0C0DA',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3839',
    name: 'Lavender Blue Medium',
    hex: '#7B8EAB',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3838',
    name: 'Lavender Blue Dark',
    hex: '#5C7294',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '800',
    name: 'Delft Blue Pale',
    hex: '#C0CCDE',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '809',
    name: 'Delft Blue',
    hex: '#94A8C6',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '799',
    name: 'Delft Blue Medium',
    hex: '#748EB6',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '798',
    name: 'Delft Blue Dark',
    hex: '#466A8E',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '797',
    name: 'Royal Blue',
    hex: '#13477D',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '796',
    name: 'Royal Blue Dark',
    hex: '#11416D',
    category: 'blue',
    range: '700',
    family: '6',
  },
  {
    code: '820',
    name: 'Royal Blue Very Dark',
    hex: '#0E365C',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '162',
    name: 'Blue Ultra Very Light',
    hex: '#DBECF5',
    category: 'blue',
    range: '100',
    family: '6',
  },
  {
    code: '827',
    name: 'Blue Very Light',
    hex: '#BDDDED',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '813',
    name: 'Blue Light',
    hex: '#A1C2D7',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '826',
    name: 'Blue Medium',
    hex: '#6B9EBF',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '825',
    name: 'Blue Dark',
    hex: '#4781A5',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '824',
    name: 'Blue Very Dark',
    hex: '#396987',
    category: 'blue',
    range: '800',
    family: '6',
  },
  {
    code: '996',
    name: 'Electric Blue Medium',
    hex: '#30C2EC',
    category: 'blue',
    range: '900',
    family: '6',
  },
  {
    code: '3843',
    name: 'Electric Blue',
    hex: '#14AAD0',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '995',
    name: 'Electric Blue Dark',
    hex: '#2696B6',
    category: 'blue',
    range: '900',
    family: '6',
  },
  {
    code: '3846',
    name: 'Turquoise Bright Light',
    hex: '#06E3E6',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3845',
    name: 'Turquoise Bright Medium',
    hex: '#04C4CA',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '3844',
    name: 'Turquoise Bright Dark',
    hex: '#12AEBA',
    category: 'blue',
    range: '3000',
    family: '6',
  },
  {
    code: '159',
    name: 'Blue Gray Light',
    hex: '#C7CAD7',
    category: 'sapphire',
    range: '100',
    family: '7',
  },
  {
    code: '160',
    name: 'Blue Gray Medium',
    hex: '#999FB7',
    category: 'sapphire',
    range: '100',
    family: '7',
  },
  {
    code: '161',
    name: 'Blue Gray',
    hex: '#7880A4',
    category: 'sapphire',
    range: '100',
    family: '7',
  },
  {
    code: '3756',
    name: 'Baby Blue Ultra Very Light',
    hex: '#EEFCFC',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '775',
    name: 'Baby Blue Very Light',
    hex: '#D9EBF1',
    category: 'sapphire',
    range: '700',
    family: '7',
  },
  {
    code: '3841',
    name: 'Baby Blue Pale',
    hex: '#CDDFED',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '3325',
    name: 'Baby Blue Light',
    hex: '#B8D2E6',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '3755',
    name: 'Baby Blue',
    hex: '#92B4CE',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '334',
    name: 'Baby Blue Medium',
    hex: '#739FC1',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '322',
    name: 'Baby Blue Dark',
    hex: '#5A8FB8',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '312',
    name: 'Baby Blue Very Dark',
    hex: '#35668B',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '803',
    name: 'Baby Blue Ultra Very Dark',
    hex: '#2C597C',
    category: 'sapphire',
    range: '800',
    family: '7',
  },
  {
    code: '336',
    name: 'Navy Blue',
    hex: '#253B73',
    category: 'sapphire',
    range: '300',
    family: '7',
  },
  {
    code: '823',
    name: 'Navy Blue Dark',
    hex: '#213063',
    category: 'sapphire',
    range: '800',
    family: '7',
  },
  {
    code: '939',
    name: 'Navy Blue Very Dark',
    hex: '#1B2853',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '3753',
    name: 'Antique Blue Ultra Very Light',
    hex: '#DBE2E9',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '3752',
    name: 'Antique Blue Very Light',
    hex: '#C7D1DB',
    category: 'sapphire',
    range: '3000',
    family: '7',
  },
  {
    code: '932',
    name: 'Antique Blue Light',
    hex: '#A2B5C6',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '931',
    name: 'Antique Blue Medium',
    hex: '#6A859E',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '930',
    name: 'Antique Blue Dark',
    hex: '#455C71',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '3750',
    name: 'Antique Blue Very Dark',
    hex: '#384C5E',
    category: 'sapphire',
    range: '900',
    family: '7',
  },
  {
    code: '828',
    name: 'Sky Blue Very Light',
    hex: '#C5E8ED',
    category: 'blue-green',
    range: '800',
    family: '8',
  },
  {
    code: '3761',
    name: 'Sky Blue Light',
    hex: '#ACD8E2',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '519',
    name: 'Sky Blue',
    hex: '#7EB1C8',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '518',
    name: 'Wedgewood Light',
    hex: '#4F93A7',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '3760',
    name: 'Wedgewood Medium',
    hex: '#3E85A2',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '517',
    name: 'Wedgewood Dark',
    hex: '#3B768F',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '3842',
    name: 'Wedgewood Very Dark',
    hex: '#32667C',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '311',
    name: 'Wedgewood Ultra Very Dark',
    hex: '#1C5066',
    category: 'blue-green',
    range: '300',
    family: '8',
  },
  {
    code: '747',
    name: 'Peacock Blue Very Light',
    hex: '#E5FCFD',
    category: 'blue-green',
    range: '700',
    family: '8',
  },
  {
    code: '3766',
    name: 'Peacock Blue Light',
    hex: '#99CFD9',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '807',
    name: 'Peacock Blue',
    hex: '#64ABBA',
    category: 'blue-green',
    range: '800',
    family: '8',
  },
  {
    code: '806',
    name: 'Peacock Blue Dark',
    hex: '#3D95A5',
    category: 'blue-green',
    range: '800',
    family: '8',
  },
  {
    code: '3765',
    name: 'Peacock Blue Very Dark',
    hex: '#347F8C',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3811',
    name: 'Turquoise Very Light',
    hex: '#BCE3E6',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '598',
    name: 'Turquoise Light',
    hex: '#90C3CC',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '597',
    name: 'Turquoise',
    hex: '#5BA3B3',
    category: 'blue-green',
    range: '500',
    family: '8',
  },
  {
    code: '3810',
    name: 'Turquoise Dark',
    hex: '#488E9A',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3809',
    name: 'Turquoise Very Dark',
    hex: '#3F7C85',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3808',
    name: 'Turquoise Ultra Very Dark',
    hex: '#366970',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '928',
    name: 'Gray Green Very Light',
    hex: '#DDE3E3',
    category: 'blue-green',
    range: '900',
    family: '8',
  },
  {
    code: '927',
    name: 'Gray Green Light',
    hex: '#BDCBCB',
    category: 'blue-green',
    range: '900',
    family: '8',
  },
  {
    code: '926',
    name: 'Gray Green Medium',
    hex: '#98AEAE',
    category: 'blue-green',
    range: '900',
    family: '8',
  },
  {
    code: '3768',
    name: 'Gray Green Dark',
    hex: '#657F7F',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3849',
    name: 'Teal Green Light',
    hex: '#52B3AE',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3848',
    name: 'Teal Green Medium',
    hex: '#419392',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '3847',
    name: 'Teal Green Dark',
    hex: '#347D75',
    category: 'blue-green',
    range: '3000',
    family: '8',
  },
  {
    code: '964',
    name: 'Sea Green Light',
    hex: '#347D75',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '959',
    name: 'Sea Green Medium',
    hex: '#59C7B4',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '958',
    name: 'Sea Green Dark',
    hex: '#3EB6A1',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '3812',
    name: 'Sea Green Very Dark',
    hex: '#2F8C84',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '3851',
    name: 'Green Bright Light',
    hex: '#49B3A1',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '943',
    name: 'Green Bright Medium',
    hex: '#3D9384',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '3850',
    name: 'Green Bright Dark',
    hex: '#378477',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '993',
    name: 'Aquamarine Very Light',
    hex: '#90C0B4',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '992',
    name: 'Aquamarine Light',
    hex: '#6FAE9F',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '3814',
    name: 'Aquamarine',
    hex: '#508B7D',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '991',
    name: 'Aquamarine Dark',
    hex: '#477B6E',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '966',
    name: 'Jade Ultra Very Light',
    hex: '#B9D7C0',
    category: 'green',
    range: '900',
    family: '9',
  },
  {
    code: '564',
    name: 'Jade Very Light',
    hex: '#A7CDAF',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '564',
    name: 'Jade Very Light',
    hex: '#A7CDAF',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '563',
    name: 'Jade Light',
    hex: '#8FC098',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '562',
    name: 'Jade Medium',
    hex: '#53976A',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '505',
    name: 'Jade Green',
    hex: '#338362',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '3817',
    name: 'Celadon Green Light',
    hex: '#99C3AA',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '3816',
    name: 'Celadon Green',
    hex: '#65A57D',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '163',
    name: 'Celadon Green Medium',
    hex: '#4D8361',
    category: 'green',
    range: '100',
    family: '9',
  },
  {
    code: '3815',
    name: 'Celadon Green Dark',
    hex: '#477759',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '561',
    name: 'Celadon Green Very Dark',
    hex: '#2C6A45',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '504',
    name: 'Blue Green Very Light',
    hex: '#C4DECC',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '3813',
    name: 'Blue Green Light',
    hex: '#B2D4BD',
    category: 'green',
    range: '3000',
    family: '9',
  },
  {
    code: '503',
    name: 'Blue Green Medium',
    hex: '#7BAC94',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '502',
    name: 'Blue Green',
    hex: '#5B9071',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '501',
    name: 'Blue Green Dark',
    hex: '#396F52',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '500',
    name: 'Blue Green Very Dark',
    hex: '#044D33',
    category: 'green',
    range: '500',
    family: '9',
  },
  {
    code: '955',
    name: 'Light Nile Green',
    hex: '#A2D6AD',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '13',
    name: 'Nile Green Medium Light',
    hex: '#BFF6E0',
    category: 'green-yellow',
    range: '10',
    family: '10',
  },
  {
    code: '954',
    name: 'Nile Green',
    hex: '#88BA91',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '913',
    name: 'Nile Green Medium',
    hex: '#6DAB77',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '912',
    name: 'Emerald Green Light',
    hex: '#1B9D6B',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '911',
    name: 'Emerald Green Medium',
    hex: '#1B9D6B',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '910',
    name: 'Emerald Green Dark',
    hex: '#187E56',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '909',
    name: 'Emerald Green Very Dark',
    hex: '#156F49',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '3818',
    name: 'Emerald Green Ultra Very Dark',
    hex: '#115A3B',
    category: 'green-yellow',
    range: '3000',
    family: '10',
  },
  {
    code: '369',
    name: 'Pistachio Green Very Light',
    hex: '#D7EDCC',
    category: 'green-yellow',
    range: '300',
    family: '10',
  },
  {
    code: '368',
    name: 'Pistachio Green Light',
    hex: '#A6C298',
    category: 'green-yellow',
    range: '300',
    family: '10',
  },
  {
    code: '320',
    name: 'Pistachio Green Medium',
    hex: '#69885A',
    category: 'green-yellow',
    range: '300',
    family: '10',
  },
  {
    code: '367',
    name: 'Pistachio Green Dark',
    hex: '#617A52',
    category: 'green-yellow',
    range: '300',
    family: '10',
  },
  {
    code: '319',
    name: 'Pistachio Green Very Dark',
    hex: '#205F2E',
    category: 'green-yellow',
    range: '300',
    family: '10',
  },
  {
    code: '890',
    name: 'Pistachio Green Ultra Very Dark',
    hex: '#184923',
    category: 'green-yellow',
    range: '800',
    family: '10',
  },
  {
    code: '164',
    name: 'Forest Green Light',
    hex: '#C8D8B8',
    category: 'green-yellow',
    range: '100',
    family: '10',
  },
  {
    code: '989',
    name: 'Forest Green',
    hex: '#8DA675',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '988',
    name: 'Forest Green Medium',
    hex: '#738B5B',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '987',
    name: 'Forest Green Dark',
    hex: '#587141',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '986',
    name: 'Forest Green Very Dark',
    hex: '#405230',
    category: 'green-yellow',
    range: '900',
    family: '10',
  },
  {
    code: '772',
    name: 'Yellow Green Very Light',
    hex: '#E4ECD4',
    category: 'green-yellow',
    range: '700',
    family: '10',
  },
  {
    code: '3348',
    name: 'Yellow Green Light',
    hex: '#CCD9B1',
    category: 'green-yellow',
    range: '3000',
    family: '10',
  },
  {
    code: '3347',
    name: 'Yellow Green Medium',
    hex: '#71935C',
    category: 'green-yellow',
    range: '3000',
    family: '10',
  },
  {
    code: '3346',
    name: 'Hunter Green',
    hex: '#406A3A',
    category: 'green-yellow',
    range: '3000',
    family: '10',
  },
  {
    code: '3345',
    name: 'Hunter Green Dark',
    hex: '#1B5915',
    category: 'green-yellow',
    range: '3000',
    family: '10',
  },
  {
    code: '895',
    name: 'Hunter Green Very Dark',
    hex: '#1B5300',
    category: 'green-yellow',
    range: '3000',
    family: '10',
  },
  {
    code: '14',
    name: 'Apple Green Pale',
    hex: '#D0FBB2',
    category: 'green',
    range: '10',
    family: '11',
  },
  {
    code: '15',
    name: 'Apple Green',
    hex: '#D0FBB2',
    category: 'green',
    range: '10',
    family: '11',
  },
  {
    code: '16',
    name: 'Chartreuse Light',
    hex: '#dcf062',
    category: 'green',
    range: '10',
    family: '11',
  },
  {
    code: '704',
    name: 'Chartreuse Bright',
    hex: '#9ECF34',
    category: 'green',
    range: '700',
    family: '11',
  },
  {
    code: '703',
    name: 'Chartreuse',
    hex: '#7BB547',
    category: 'green',
    range: '700',
    family: '11',
  },
  {
    code: '702',
    name: 'Kelly Green',
    hex: '#47A72F',
    category: 'green',
    range: '700',
    family: '11',
  },
  {
    code: '701',
    name: 'Green Light',
    hex: '#3F8F29',
    category: 'green',
    range: '700',
    family: '11',
  },
  {
    code: '700',
    name: 'Green Bright',
    hex: '#07731B',
    category: 'green',
    range: '700',
    family: '11',
  },
  {
    code: '699',
    name: 'Green',
    hex: '#056517',
    category: 'green',
    range: '600',
    family: '11',
  },
  {
    code: '907',
    name: 'Parrot Green Light',
    hex: '#C7E666',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '906',
    name: 'Parrot Green Medium',
    hex: '#7FB335',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '905',
    name: 'Parrot Green Dark',
    hex: '#628A28',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '904',
    name: 'Parrot Green Very Dark',
    hex: '#557822',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '472',
    name: 'Avocado Green Ultra Light',
    hex: '#D8E498',
    category: 'green',
    range: '400',
    family: '11',
  },
  {
    code: '471',
    name: 'Avocado Green Very Light',
    hex: '#AEBF79',
    category: 'green',
    range: '400',
    family: '11',
  },
  {
    code: '470',
    name: 'Avocado Green Light',
    hex: '#94AB4F',
    category: 'green',
    range: '400',
    family: '11',
  },
  {
    code: '469',
    name: 'Avocado Green',
    hex: '#72843C',
    category: 'green',
    range: '400',
    family: '11',
  },
  {
    code: '937',
    name: 'Avocado Green Medium',
    hex: '#627133',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '936',
    name: 'Avocado Green Very Dark',
    hex: '#4C5826',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '935',
    name: 'Avocado Green Dark',
    hex: '#424D21',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '934',
    name: 'Avocado Green Black',
    hex: '#313919',
    category: 'green',
    range: '900',
    family: '11',
  },
  {
    code: '3364',
    name: 'Pine Green',
    hex: '#83975F',
    category: 'green',
    range: '3000',
    family: '11',
  },
  {
    code: '3363',
    name: 'Pine Green Medium',
    hex: '#728256',
    category: 'green',
    range: '3000',
    family: '11',
  },
  {
    code: '3362',
    name: 'Pine Green Dark',
    hex: '#5E6B47',
    category: 'green',
    range: '3000',
    family: '11',
  },
  {
    code: '10',
    name: 'Tender Green Very Light',
    hex: '#EDFED9',
    category: 'yellow-green',
    range: '10',
    family: '12',
  },
  {
    code: '11',
    name: 'Tender Green Light',
    hex: '#E2EDB5',
    category: 'yellow-green',
    range: '10',
    family: '12',
  },
  {
    code: '12',
    name: 'Tender Green',
    hex: '#CDD99A',
    category: 'yellow-green',
    range: '10',
    family: '12',
  },
  {
    code: '165',
    name: 'Moss Green Very Light',
    hex: '#EFF4A4',
    category: 'yellow-green',
    range: '100',
    family: '12',
  },
  {
    code: '3819',
    name: 'Moss Green Light',
    hex: '#E0E868',
    category: 'yellow-green',
    range: '3000',
    family: '12',
  },
  {
    code: '166',
    name: 'Moss Green Medium Light',
    hex: '#C0C840',
    category: 'yellow-green',
    range: '100',
    family: '12',
  },
  {
    code: '581',
    name: 'Moss Green',
    hex: '#A7AE38',
    category: 'yellow-green',
    range: '500',
    family: '12',
  },
  {
    code: '580',
    name: 'Moss Green Dark',
    hex: '#888D33',
    category: 'yellow-green',
    range: '500',
    family: '12',
  },
  {
    code: '523',
    name: 'Fern Green Light',
    hex: '#ABB197',
    category: 'yellow-green',
    range: '500',
    family: '12',
  },
  {
    code: '3053',
    name: 'Fern Gray',
    hex: '#9CA482',
    category: 'yellow-green',
    range: '3000',
    family: '12',
  },
  {
    code: '3052',
    name: 'Fern Gray Medium',
    hex: '#889268',
    category: 'yellow-green',
    range: '3000',
    family: '12',
  },
  {
    code: '3051',
    name: 'Fern Gray Dark',
    hex: '#5F6648',
    category: 'yellow-green',
    range: '3000',
    family: '12',
  },
  {
    code: '524',
    name: 'Fern Green Very Light',
    hex: '#C4CDAC',
    category: 'yellow-green',
    range: '500',
    family: '12',
  },
  {
    code: '522',
    name: 'Fern Green',
    hex: '#969E7E',
    category: 'yellow-green',
    range: '500',
    family: '12',
  },
  {
    code: '520',
    name: 'Fern Green Dark',
    hex: '#666D4F',
    category: 'yellow-green',
    range: '500',
    family: '12',
  },
  {
    code: '734',
    name: 'Olive Green Light',
    hex: '#C7C077',
    category: 'yellow-green',
    range: '700',
    family: '12',
  },
  {
    code: '733',
    name: 'Olive Green Medium',
    hex: '#BCB34C',
    category: 'yellow-green',
    range: '700',
    family: '12',
  },
  {
    code: '732',
    name: 'Olive Green',
    hex: '#948C36',
    category: 'yellow-green',
    range: '700',
    family: '12',
  },
  {
    code: '731',
    name: 'Olive Green Dark',
    hex: '#938B37',
    category: 'yellow-green',
    range: '700',
    family: '12',
  },
  {
    code: '730',
    name: 'Olive Green Very Dark',
    hex: '#827B30',
    category: 'yellow-green',
    range: '700',
    family: '12',
  },
  {
    code: '3013',
    name: 'Khaki Green Light',
    hex: '#B9B982',
    category: 'yellow-green',
    range: '3000',
    family: '12',
  },
  {
    code: '3012',
    name: 'Khaki Green Medium',
    hex: '#A6A75D',
    category: 'yellow-green',
    range: '3000',
    family: '12',
  },
  {
    code: '3011',
    name: 'Khaki Green Dark',
    hex: '#898A58',
    category: 'yellow-green',
    range: '3000',
    family: '12',
  },
  {
    code: '372',
    name: 'Mustard Light',
    hex: '#CCB784',
    category: 'yellow-green',
    range: '300',
    family: '12',
  },
  {
    code: '371',
    name: 'Mustard',
    hex: '#BFA671',
    category: 'yellow-green',
    range: '300',
    family: '12',
  },
  {
    code: '370',
    name: 'Mustard Medium',
    hex: '#B89D64',
    category: 'yellow-green',
    range: '300',
    family: '12',
  },
  {
    code: '17',
    name: 'Yellow Plum Light',
    hex: '#E5E272',
    category: 'yellow',
    range: '10',
    family: '13',
  },
  {
    code: '18',
    name: 'Yellow Plum',
    hex: '#D9D56D',
    category: 'yellow',
    range: '10',
    family: '13',
  },
  {
    code: '834',
    name: 'Golden Olive Very Light',
    hex: '#DBBE7F',
    category: 'gold',
    range: '800',
    family: '13',
  },
  {
    code: '833',
    name: 'Golden Olive Light',
    hex: '#C8AB6C',
    category: 'gold',
    range: '800',
    family: '13',
  },
  {
    code: '832',
    name: 'Golden Olive',
    hex: '#BD9B51',
    category: 'gold',
    range: '800',
    family: '13',
  },
  {
    code: '831',
    name: 'Golden Olive Medium',
    hex: '#AA8F56',
    category: 'gold',
    range: '800',
    family: '13',
  },
  {
    code: '830',
    name: 'Golden Olive Dark',
    hex: '#8D784B',
    category: 'gold',
    range: '800',
    family: '13',
  },
  {
    code: '830',
    name: 'Golden Olive Very Dark',
    hex: '#7E6B42',
    category: 'gold',
    range: '800',
    family: '13',
  },
  {
    code: '746',
    name: 'Off White',
    hex: '#FCFCEE',
    category: 'neutral',
    range: '700',
    family: '13',
  },
  {
    code: '677',
    name: 'Old Gold Very Light',
    hex: '#F5ECCB',
    category: 'gold',
    range: '600',
    family: '13',
  },
  {
    code: '422',
    name: 'Haxelnut Brown Light',
    hex: '#C69F7B',
    category: 'brown',
    range: '400',
    family: '13',
  },
  {
    code: '3828',
    name: 'Haxelnut Brown',
    hex: '#B78B61',
    category: 'brown',
    range: '3000',
    family: '13',
  },
  {
    code: '420',
    name: 'Haxelnut Brown Dark',
    hex: '#A07042',
    category: 'brown',
    range: '400',
    family: '13',
  },
  {
    code: '869',
    name: 'Haxelnut Brown Very Dark',
    hex: '#835E39',
    category: 'brown',
    range: '800',
    family: '13',
  },
  {
    code: '613',
    name: 'Drab Brown Very Light',
    hex: '#DCC4AA',
    category: 'brown',
    range: '600',
    family: '13',
  },
  {
    code: '612',
    name: 'Drab Brown Light',
    hex: '#BC9A78',
    category: 'brown',
    range: '600',
    family: '13',
  },
  {
    code: '611',
    name: 'Drab Brown',
    hex: '#967656',
    category: 'brown',
    range: '600',
    family: '13',
  },
  {
    code: '610',
    name: 'Drab Brown Dark',
    hex: '#796047',
    category: 'brown',
    range: '600',
    family: '13',
  },
  {
    code: '3047',
    name: 'Yellow Beige Light',
    hex: '#E7D6C1',
    category: 'yellow',
    range: '3000',
    family: '13',
  },
  {
    code: '3046',
    name: 'Yellow Beige Medium',
    hex: '#D8BC9A',
    category: 'yellow',
    range: '3000',
    family: '13',
  },
  {
    code: '3045',
    name: 'Yellow Beige Dark',
    hex: '#BC966A',
    category: 'yellow',
    range: '3000',
    family: '13',
  },
  {
    code: '167',
    name: 'Yellow Beige Very Dark',
    hex: '#A77C49',
    category: 'yellow',
    range: '100',
    family: '13',
  },
  {
    code: '676',
    name: 'Old Gold Light',
    hex: '#E5CE97',
    category: 'gold',
    range: '600',
    family: '14',
  },
  {
    code: '729',
    name: 'Old Gold Medium',
    hex: '#D0A53E',
    category: 'gold',
    range: '700',
    family: '14',
  },
  {
    code: '680',
    name: 'Old Gold Dark',
    hex: '#BC8D0E',
    category: 'gold',
    range: '600',
    family: '14',
  },
  {
    code: '3829',
    name: 'Old Gold Very Dark',
    hex: '#A98204',
    category: 'gold',
    range: '3000',
    family: '14',
  },
  {
    code: '3822',
    name: 'Straw Light',
    hex: '#F6DC98',
    category: 'yellow',
    range: '3000',
    family: '14',
  },
  {
    code: '3821',
    name: 'Straw',
    hex: '#F3CE75',
    category: 'yellow',
    range: '3000',
    family: '14',
  },
  {
    code: '3820',
    name: 'Straw Dark',
    hex: '#DFB65F',
    category: 'yellow',
    range: '3000',
    family: '14',
  },
  {
    code: '3852',
    name: 'Straw Very Dark',
    hex: '#CD9D37',
    category: 'yellow',
    range: '3000',
    family: '14',
  },
  {
    code: '728',
    name: 'Topaz',
    hex: '#E4B468',
    category: 'gold',
    range: '700',
    family: '14',
  },
  {
    code: '783',
    name: 'Topaz Medium',
    hex: '#CE9124',
    category: 'gold',
    range: '700',
    family: '14',
  },
  {
    code: '782',
    name: 'Topaz Dark',
    hex: '#AE7720',
    category: 'gold',
    range: '700',
    family: '14',
  },
  {
    code: '781',
    name: 'Topaz Very Dark',
    hex: '#A26D20',
    category: 'gold',
    range: '700',
    family: '14',
  },
  {
    code: '780',
    name: 'Topaz Ultra Very Dark',
    hex: '#94631A',
    category: 'gold',
    range: '700',
    family: '14',
  },
  {
    code: '3823',
    name: 'Yellow Ultra Pale',
    hex: '#FFFDE3',
    category: 'yellow',
    range: '3000',
    family: '14',
  },
  {
    code: '3855',
    name: 'Autumn Gold Light',
    hex: '#FAD396',
    category: 'gold',
    range: '3000',
    family: '14',
  },
  {
    code: '19',
    name: 'Autumn Gold Medium Light',
    hex: '#F7C95F',
    category: 'gold',
    range: '10',
    family: '14',
  },
  {
    code: '3854',
    name: 'Autumn Gold Medium',
    hex: '#F2AF68',
    category: 'gold',
    range: '3000',
    family: '14',
  },
  {
    code: '3853',
    name: 'Autumn Gold Dark',
    hex: '#F29746',
    category: 'gold',
    range: '3000',
    family: '14',
  },
  {
    code: '3827',
    name: 'Golden Brown Dark',
    hex: '#F7BB77',
    category: 'gold',
    range: '3000',
    family: '14',
  },
  {
    code: '3827',
    name: 'Golden Brown Pale',
    hex: '#DC9C56',
    category: 'gold',
    range: '3000',
    family: '14',
  },
  {
    code: '977',
    name: 'Golden Brown Light',
    hex: '#DC9C56',
    category: 'gold',
    range: '900',
    family: '14',
  },
  {
    code: '976',
    name: 'Golden Brown Medium',
    hex: '#C28142',
    category: 'gold',
    range: '900',
    family: '14',
  },
  {
    code: '3826',
    name: 'Golden Brown',
    hex: '#AD7239',
    category: 'gold',
    range: '3000',
    family: '14',
  },
  {
    code: '975',
    name: 'Golden Brown Dark',
    hex: '#914F12',
    category: 'gold',
    range: '900',
    family: '14',
  },
  {
    code: '445',
    name: 'Lemon Light',
    hex: '#FFFB8B',
    category: 'yellow',
    range: '400',
    family: '15',
  },
  {
    code: '307',
    name: 'Lemon',
    hex: '#FDED54',
    category: 'yellow',
    range: '300',
    family: '15',
  },
  {
    code: '973',
    name: 'Canary Bright',
    hex: '#FFE300',
    category: 'yellow',
    range: '900',
    family: '15',
  },
  {
    code: '444',
    name: 'Lemon Dark',
    hex: '#FFD600',
    category: 'yellow',
    range: '400',
    family: '15',
  },
  {
    code: '3078',
    name: 'Golden Yellow Very Light',
    hex: '#FDF9CD',
    category: 'yellow',
    range: '3000',
    family: '15',
  },
  {
    code: '727',
    name: 'Topaz Very Light',
    hex: '#FFF1AF',
    category: 'yellow',
    range: '700',
    family: '15',
  },
  {
    code: '726',
    name: 'Topaz Light',
    hex: '#FDD755',
    category: 'yellow',
    range: '700',
    family: '15',
  },
  {
    code: '725',
    name: 'Topaz Medium Light',
    hex: '#FFC840',
    category: 'yellow',
    range: '700',
    family: '15',
  },
  {
    code: '972',
    name: 'Canary Deep',
    hex: '#FFB515',
    category: 'yellow',
    range: '900',
    family: '15',
  },
  {
    code: '745',
    name: 'Yellow Pale Light',
    hex: '#FFE9AD',
    category: 'yellow',
    range: '700',
    family: '15',
  },
  {
    code: '744',
    name: 'Yellow Pale',
    hex: '#FFE793',
    category: 'yellow',
    range: '700',
    family: '15',
  },
  {
    code: '743',
    name: 'Yellow Medium',
    hex: '#FED376',
    category: 'yellow',
    range: '700',
    family: '15',
  },
  {
    code: '742',
    name: 'Tangerine Light',
    hex: '#FFBF57',
    category: 'orange',
    range: '700',
    family: '15',
  },
  {
    code: '741',
    name: 'Tangerine Medium',
    hex: '#FFA32B',
    category: 'orange',
    range: '700',
    family: '15',
  },
  {
    code: '740',
    name: 'Tangerine',
    hex: '#FF8B00',
    category: 'orange',
    range: '700',
    family: '15',
  },
  {
    code: '970',
    name: 'Pumpkin Light',
    hex: '#F78B13',
    category: 'orange',
    range: '900',
    family: '15',
  },
  {
    code: '971',
    name: 'Pumpkin',
    hex: '#F67F00',
    category: 'orange',
    range: '900',
    family: '15',
  },
  {
    code: '947',
    name: 'Burnt Orange',
    hex: '#FF7B4D',
    category: 'orange',
    range: '900',
    family: '15',
  },
  {
    code: '946',
    name: 'Burnt Orange Medium',
    hex: '#EB6307',
    category: 'orange',
    range: '900',
    family: '15',
  },
  {
    code: '900',
    name: 'Burnt Orange Dark',
    hex: '#D15807',
    category: 'orange',
    range: '900',
    family: '15',
  },
  {
    code: '967',
    name: 'Apricot Very Light',
    hex: '#FFDED5',
    category: 'orange-red',
    range: '900',
    family: '15',
  },
  {
    code: '3824',
    name: 'Apricot Light',
    hex: '#FECDC2',
    category: 'orange-red',
    range: '3000',
    family: '15',
  },
  {
    code: '3341',
    name: 'Apricot',
    hex: '#FCAB98',
    category: 'orange-red',
    range: '3000',
    family: '15',
  },
  {
    code: '3340',
    name: 'Apricot Medium',
    hex: '#FF836F',
    category: 'orange-red',
    range: '3000',
    family: '15',
  },
  {
    code: '608',
    name: 'Burnt Orange Bright',
    hex: '#FD5D35',
    category: 'orange-red',
    range: '600',
    family: '15',
  },
  {
    code: '606',
    name: 'Orange Red Bright',
    hex: '#FA3203',
    category: 'orange-red',
    range: '600',
    family: '15',
  },
  {
    code: '951',
    name: 'Tawny Light',
    hex: '#FFE2CF',
    category: 'orange',
    range: '900',
    family: '16',
  },
  {
    code: '3856',
    name: 'Mahogany Ultra Very Light',
    hex: '#FFD3B5',
    category: 'orange',
    range: '3000',
    family: '16',
  },
  {
    code: '722',
    name: 'Orange Spice Light',
    hex: '#F7976F',
    category: 'orange',
    range: '700',
    family: '16',
  },
  {
    code: '721',
    name: 'Orange Spice Light',
    hex: '#F7976F',
    category: 'orange',
    range: '700',
    family: '16',
  },
  {
    code: '720',
    name: 'Orange Spice Medium',
    hex: '#F27842',
    category: 'orange',
    range: '700',
    family: '16',
  },
  {
    code: '3825',
    name: 'Pumpkin Pale',
    hex: '#FDBD96',
    category: 'orange',
    range: '3000',
    family: '16',
  },
  {
    code: '922',
    name: 'Copper Light',
    hex: '#E27323',
    category: 'red-orange',
    range: '900',
    family: '16',
  },
  {
    code: '921',
    name: 'Copper',
    hex: '#C66218',
    category: 'red-orange',
    range: '900',
    family: '16',
  },
  {
    code: '920',
    name: 'Copper Medium',
    hex: '#AC5414',
    category: 'red-orange',
    range: '900',
    family: '16',
  },
  {
    code: '919',
    name: 'Red Copper',
    hex: '#A64510',
    category: 'red-orange',
    range: '900',
    family: '16',
  },
  {
    code: '918',
    name: 'Red Copper Dark',
    hex: '#82340A',
    category: 'red-orange',
    range: '900',
    family: '16',
  },
  {
    code: '3770',
    name: 'Tawny Very Light',
    hex: '#FFEEE3',
    category: 'orange',
    range: '3000',
    family: '16',
  },
  {
    code: '945',
    name: 'Tawny',
    hex: '#FBD5BB',
    category: 'orange',
    range: '900',
    family: '16',
  },
  {
    code: '402',
    name: 'Mahogany Very Light',
    hex: '#F7A777',
    category: 'orange',
    range: '400',
    family: '16',
  },
  {
    code: '3776',
    name: 'Mahogany Light',
    hex: '#CF7939',
    category: 'orange',
    range: '3000',
    family: '16',
  },
  {
    code: '301',
    name: 'Mahogany Medium',
    hex: '#B35F2B',
    category: 'orange',
    range: '300',
    family: '16',
  },
  {
    code: '400',
    name: 'Mahogany Dark',
    hex: '#8F430F',
    category: 'orange',
    range: '400',
    family: '16',
  },
  {
    code: '300',
    name: 'Mahogany Very Dark',
    hex: '#6F2F00',
    category: 'orange',
    range: '300',
    family: '16',
  },
  {
    code: '225',
    name: 'Shell Pink Ultra Very Light',
    hex: '#FFDFD7',
    category: 'pink',
    range: '200',
    family: '16',
  },
  {
    code: '224',
    name: 'Shell Pink Very Light',
    hex: '#EBB7AF',
    category: 'pink',
    range: '200',
    family: '16',
  },
  {
    code: '152',
    name: 'Shell Pink Medium Light',
    hex: '#E2A099',
    category: 'pink',
    range: '100',
    family: '16',
  },
  {
    code: '223',
    name: 'Shell Pink Light',
    hex: '#CC847C',
    category: 'pink',
    range: '200',
    family: '16',
  },
  {
    code: '3722',
    name: 'Shell Pink Medium',
    hex: '#BC6C64',
    category: 'pink',
    range: '3000',
    family: '16',
  },
  {
    code: '3721',
    name: 'Shell Pink Dark',
    hex: '#A14B51',
    category: 'pink',
    range: '3000',
    family: '16',
  },
  {
    code: '221',
    name: 'Shell Pink Very Dark',
    hex: '#883E43',
    category: 'pink',
    range: '200',
    family: '16',
  },
  {
    code: '948',
    name: 'Peach Very Light',
    hex: '#FEE7DA',
    category: 'pink',
    range: '900',
    family: '17',
  },
  {
    code: '754',
    name: 'Peach Light',
    hex: '#F7CBBF',
    category: 'pink',
    range: '700',
    family: '17',
  },
  {
    code: '3771',
    name: 'Terra Cotta Ultra Very Light',
    hex: '#F4BBA9',
    category: 'orange-red',
    range: '3000',
    family: '17',
  },
  {
    code: '758',
    name: 'Terra Cotta Very Light',
    hex: '#EEAA9B',
    category: 'orange-red',
    range: '700',
    family: '17',
  },
  {
    code: '3778',
    name: 'Terra Cotta Light',
    hex: '#D98978',
    category: 'orange-red',
    range: '3000',
    family: '17',
  },
  {
    code: '356',
    name: 'Terra Cotta Medium',
    hex: '#C56A5B',
    category: 'orange-red',
    range: '300',
    family: '17',
  },
  {
    code: '3830',
    name: 'Terra Cotta',
    hex: '#BC5544',
    category: 'orange-red',
    range: '3000',
    family: '17',
  },
  {
    code: '355',
    name: 'Terra Cotta Dark',
    hex: '#984436',
    category: 'orange-red',
    range: '300',
    family: '17',
  },
  {
    code: '3777',
    name: 'Terra Cotta Very Dark',
    hex: '#863022',
    category: 'orange-red',
    range: '3000',
    family: '17',
  },
  {
    code: '3779',
    name: 'Rosewood Ultra Very Light',
    hex: '#F8CAC8',
    category: 'red',
    range: '3000',
    family: '17',
  },
  {
    code: '3859',
    name: 'Rosewood Light',
    hex: '#BA8B7C',
    category: 'red',
    range: '3000',
    family: '17',
  },
  {
    code: '3858',
    name: 'Rosewood Medium',
    hex: '#964A3F',
    category: 'red',
    range: '3000',
    family: '17',
  },
  {
    code: '3857',
    name: 'Rosewood Dark',
    hex: '#68251A',
    category: 'red',
    range: '3000',
    family: '17',
  },
  {
    code: '20',
    name: 'Shrimp',
    hex: '#F7AF93',
    category: 'pink',
    range: '20',
    family: '17',
  },
  {
    code: '21',
    name: 'Alizarin Light',
    hex: '#D79982',
    category: 'pink',
    range: '20',
    family: '17',
  },
  {
    code: '22',
    name: 'Alizarin',
    hex: '#BC604E',
    category: 'pink',
    range: '20',
    family: '17',
  },
  {
    code: '3774',
    name: 'Desert Sand Very Light',
    hex: '#F3E1D7',
    category: 'tan',
    range: '3000',
    family: '17',
  },
  {
    code: '950',
    name: 'Desert Sand Light',
    hex: '#EED3C4',
    category: 'tan',
    range: '900',
    family: '17',
  },
  {
    code: '3064',
    name: 'Desert Sand',
    hex: '#C48E70',
    category: 'tan',
    range: '3000',
    family: '17',
  },
  {
    code: '407',
    name: 'Desert Sand Medium',
    hex: '#BB8161',
    category: 'tan',
    range: '400',
    family: '17',
  },
  {
    code: '3773',
    name: 'Desert Sand Dark',
    hex: '#B67552',
    category: 'tan',
    range: '3000',
    family: '17',
  },
  {
    code: '3772',
    name: 'Desert Sand Very Dark',
    hex: '#B67552',
    category: 'tan',
    range: '3000',
    family: '17',
  },
  {
    code: '632',
    name: 'Desert Sand Ultra Very Dark',
    hex: '#B67552',
    category: 'tan',
    range: '600',
    family: '17',
  },
  {
    code: '453',
    name: 'Shell Gray Light',
    hex: '#D7CECB',
    category: 'gray',
    range: '400',
    family: '18',
  },
  {
    code: '452',
    name: 'Shell Gray Medium',
    hex: '#C0B3AE',
    category: 'gray',
    range: '400',
    family: '18',
  },
  {
    code: '451',
    name: 'Shell Gray Dark',
    hex: '#917B73',
    category: 'gray',
    range: '400',
    family: '18',
  },
  {
    code: '3861',
    name: 'Cocoa Light',
    hex: '#A68881',
    category: 'brown',
    range: '3000',
    family: '18',
  },
  {
    code: '3860',
    name: 'Cocoa',
    hex: '#7D5D57',
    category: 'brown',
    range: '3000',
    family: '18',
  },
  {
    code: '779',
    name: 'Cocoa Dark',
    hex: '#624B45',
    category: 'brown',
    range: '700',
    family: '18',
  },
  {
    code: '09',
    name: 'Cocoa Very Dark',
    hex: '#552014',
    category: 'brown',
    range: '00',
    family: '18',
  },
  {
    code: '712',
    name: 'Cream',
    hex: '#FFFBEF',
    category: 'tan',
    range: '700',
    family: '18',
  },
  {
    code: '739',
    name: 'Tan Ultra Very Light',
    hex: '#F8E4C8',
    category: 'tan',
    range: '700',
    family: '18',
  },
  {
    code: '738',
    name: 'Tan Ultra Light',
    hex: '#ECCC9E',
    category: 'tan',
    range: '700',
    family: '18',
  },
  {
    code: '437',
    name: 'Tan Light',
    hex: '#E4BB8E',
    category: 'tan',
    range: '400',
    family: '18',
  },
  {
    code: '436',
    name: 'Tan',
    hex: '#CB9051',
    category: 'tan',
    range: '400',
    family: '18',
  },
  {
    code: '435',
    name: 'Brown Very Light',
    hex: '#B87748',
    category: 'brown',
    range: '400',
    family: '18',
  },
  {
    code: '434',
    name: 'Brown Light',
    hex: '#985E33',
    category: 'brown',
    range: '400',
    family: '18',
  },
  {
    code: '433',
    name: 'Brown Medium',
    hex: '#7A451F',
    category: 'brown',
    range: '400',
    family: '18',
  },
  {
    code: '801',
    name: 'Coffee Brown Dark',
    hex: '#653919',
    category: 'brown',
    range: '800',
    family: '18',
  },
  {
    code: '898',
    name: 'Coffee Brown Very Dark',
    hex: '#492A13',
    category: 'brown',
    range: '800',
    family: '18',
  },
  {
    code: '938',
    name: 'Coffee Brown Ultra Dark',
    hex: '#361F0E',
    category: 'brown',
    range: '800',
    family: '18',
  },
  {
    code: '3371',
    name: 'Black Brown',
    hex: '#1E1108',
    category: 'brown',
    range: '3000',
    family: '18',
  },
  {
    code: '543',
    name: 'Beige Brown Ultra Very Light',
    hex: '#F2E3CE',
    category: 'brown',
    range: '500',
    family: '18',
  },
  {
    code: '3864',
    name: 'Mocha Beige Light',
    hex: '#CBB69C',
    category: 'brown',
    range: '3000',
    family: '18',
  },
  {
    code: '3863',
    name: 'Mocha Beige Medium',
    hex: '#A4835C',
    category: 'brown',
    range: '3000',
    family: '18',
  },
  {
    code: '3863',
    name: 'Mocha Beige Dark',
    hex: '#8A6E4E',
    category: 'brown',
    range: '3000',
    family: '18',
  },
  {
    code: '3031',
    name: 'Mocha Beige Very Dark',
    hex: '#4B3C2A',
    category: 'brown',
    range: '3000',
    family: '18',
  },
  {
    code: '3865',
    name: 'Winter White',
    hex: '#F9F7F1',
    category: 'neutral',
    range: '3000',
    family: '19',
  },
  {
    code: 'ECRU',
    name: 'ECRU',
    hex: '#F0EADA',
    category: 'beige',
    range: '0',
    family: '19',
  },
  {
    code: '822',
    name: 'Beige Gray Light',
    hex: '#E7E2D3',
    category: 'beige',
    range: '800',
    family: '19',
  },
  {
    code: '644',
    name: 'Beige Gray Medium',
    hex: '#DDD8CB',
    category: 'beige',
    range: '600',
    family: '19',
  },
  {
    code: '642',
    name: 'Beige Gray Dark',
    hex: '#A49878',
    category: 'beige',
    range: '600',
    family: '19',
  },
  {
    code: '640',
    name: 'Beige Gray Very Dark',
    hex: '#857B61',
    category: 'beige',
    range: '600',
    family: '19',
  },
  {
    code: '3787',
    name: 'Brown Gray Dark',
    hex: '#625D50',
    category: 'brown',
    range: '3000',
    family: '19',
  },
  {
    code: 'B5200',
    name: 'Snow White',
    hex: '#FFFFFF',
    category: 'neutral',
    range: '0',
    family: '20',
  },
  {
    code: 'BLANC',
    name: 'White',
    hex: '#FCFBF8',
    category: 'neutral',
    range: '0',
    family: '20',
  },
  {
    code: '310',
    name: 'Black',
    hex: '#000000',
    category: 'neutral',
    range: '300',
    family: '20',
  },
];
